# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.0

    working_directory: /go/src/github.com/andytsnowden/zkillbot
    steps:
    - checkout
    - run: dep ensure
    - run: go test -v ./...
    - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./..
    - run: go build
    - run: bash <(curl -s https://codecov.io/bash)
